vich_uploader:
    db_driver: orm

    mappings:
        documents_candidate:
            uri_prefix: /candidate
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
